name: Trigger Jenkins

on:
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Get Jenkins Crumb
        id: get-crumb
        run: |
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r .crumb)
          echo "CRUMB=$CRUMB" >> $GITHUB_ENV

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/IOTHouse_Unity/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            -H "Jenkins-Crumb: $CRUMB"
